# Site settings é…ç½®ç«™ç‚¹
title: 'Stay True'
description: 'iOS developer, astronomy enthusiast'
keyword: 'Stay True, liaoyuanng, iOS'
url: 'liaoyuanng.xyz' # your host
baseurl: ''

# Navigation links
nav:
  ğŸŒŸTimeCapsule: 'https://www.notion.so/liaoyuan/7bd2ceb734a448aba9d7340ca0f440ed?v=e7b64585a64e41f4a1f44ea5f546d9d7'
  home: '/'
  tags: '/tags.html'

# Author é…ç½®åšä¸»ä¿¡æ¯
author: 'liaoyuanng'
nickname: 'Leo'
bio: 'iOS æ¬ç –ï¼Œä¸šä½™å¤©æ–‡çˆ±å¥½è€…'
avatar: 'assets/img/profile.png'

# Search
search: true

# Night mode
nightMode: false

# Comments
disqus: false

# Share
social-share: true
social-share-items: ['wechat','weibo', 'twitter']

# theme color ä¸»é¢˜çš®è‚¤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings é…ç½®ç¤¾äº¤ç½‘ç«™url: weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  # weibo: '//weibo.com/u/2738809475'
  # juejin: '//juejin.im/user/5872f9822f301e0057490c89'
  instagram: 'https://www.notion.so/liaoyuan/7bd2ceb734a448aba9d7340ca0f440ed?v=e7b64585a64e41f4a1f44ea5f546d9d7'
  github: '//github.com/liaoyuanng'
  # jianshu: '//jianshu.com/u/f386d4a61d33'
  email: 'mailto:liaoyuanng@gmail.com'
# Tags è®¾ç½®æ ‡ç­¾
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']
timezone: Asia/Shanghai

permalink: /:categories/:title/

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

RSS: true

# Plugins
plugins: [jekyll-paginate, jekyll-seo-tag]